### ISSUE TITLE
aws-pds-l8-catalog throws ArrayIndexOutOfBoundsException: 9

### ISSUE THREAD

**Issue by vpipkt** [locationtech/rasterframes#186]
See circle ci build 821 for example. i am getting the same in my local environment. 

```
[info] Representing L8 scenes as a Spark data source
19/07/16 08:10:12 WARN BlockManager: Putting block rdd_8_2 failed due to exception java.lang.ArrayIndexOutOfBoundsException: 9.
19/07/16 08:10:12 WARN BlockManager: Putting block rdd_8_3 failed due to exception java.lang.ArrayIndexOutOfBoundsException: 9.
19/07/16 08:10:12 WARN BlockManager: Putting block rdd_8_0 failed due to exception java.lang.ArrayIndexOutOfBoundsException: 9.
19/07/16 08:10:12 WARN BlockManager: Putting block rdd_8_1 failed due to exception java.lang.ArrayIndexOutOfBoundsException: 9.
19/07/16 08:10:12 WARN BlockManager: Block rdd_8_1 could not be removed as it was not found on disk or in memory
19/07/16 08:10:12 WARN BlockManager: Block rdd_8_2 could not be removed as it was not found on disk or in memory
19/07/16 08:10:12 WARN BlockManager: Block rdd_8_0 could not be removed as it was not found on disk or in memory
19/07/16 08:10:12 WARN BlockManager: Block rdd_8_3 could not be removed as it was not found on disk or in memory
19/07/16 08:10:12 ERROR Executor: Exception in task 0.0 in stage 1.0 (TID 1)
java.lang.ArrayIndexOutOfBoundsException: 9
	at org.apache.spark.sql.catalyst.expressions.GenericRow.get(rows.scala:174)
	at org.apache.spark.sql.Row$class.apply(Row.scala:163)
	at org.apache.spark.sql.catalyst.expressions.GenericRow.apply(rows.scala:166)
	at org.apache.spark.sql.execution.RDDConversions$$anonfun$rowToRowRdd$1$$anonfun$apply$3.apply(ExistingRDD.scala:60)
	at org.apache.spark.sql.execution.RDDConversions$$anonfun$rowToRowRdd$1$$anonfun$apply$3.apply(ExistingRDD.scala:57)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:410)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$10$$anon$1.hasNext(WholeStageCodegenExec.scala:614)
	at org.apache.spark.sql.execution.columnar.InMemoryRelation$$anonfun$2$$anon$1.hasNext(InMemoryRelation.scala:149)
	at org.apache.spark.storage.memory.MemoryStore.putIteratorAsValues(MemoryStore.scala:216)
	at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1094)
	at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1085)
	at org.apache.spark.storage.BlockManager.doPut(BlockManager.scala:1020)
	at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:1085)
	at org.apache.spark.storage.BlockManager.getOrElseUpdate(BlockManager.scala:811)
	at org.apache.spark.rdd.RDD.getOrCompute(RDD.scala:335)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:286)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:49)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:49)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:49)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:49)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
	at org.apache.spark.scheduler.Task.run(Task.scala:109)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
19/07/16 08:10:12 ERROR Executor: Exception in task 3.0 in stage 1.0 (TID 4)
java.lang.ArrayIndexOutOfBoundsException: 9
	at org.apache.spark.sql.catalyst.expressions.GenericRow.get(rows.scala:174)
	at org.apache.spark.sql.Row$class.apply(Row.scala:163)
	at org.apache.spark.sql.catalyst.expressions.GenericRow.apply(rows.scala:166)
	at org.apache.spark.sql.execution.RDDConversions$$anonfun$rowToRowRdd$1$$anonfun$apply$3.apply(ExistingRDD.scala:60)
	at org.apache.spark.sql.execution.RDDConversions$$anonfun$rowToRowRdd$1$$anonfun$apply$3.apply(ExistingRDD.scala:57)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:410)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$10$$anon$1.hasNext(WholeStageCodegenExec.scala:614)
	at org.apache.spark.sql.execution.columnar.InMemoryRelation$$anonfun$2$$anon$1.hasNext(InMemoryRelation.scala:149)
	at org.apache.spark.storage.memory.MemoryStore.putIteratorAsValues(MemoryStore.scala:216)
	at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1094)
	at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1085)
	at org.apache.spark.storage.BlockManager.doPut(BlockManager.scala:1020)
	at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:1085)
	at org.apache.spark.storage.BlockManager.getOrElseUpdate(BlockManager.scala:811)
	at org.apache.spark.rdd.RDD.getOrCompute(RDD.scala:335)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:286)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:49)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:49)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:49)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:49)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
	at org.apache.spark.scheduler.Task.run(Task.scala:109)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by metasim** [comment]
This is also suspicious output:
```
[info] Compiling 3 Scala sources to /home/circleci/repo/experimental/target/scala-2.11/it-classes ...
GDAL version: GDAL 2.4.1, released 2019/03/15���������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������
[info] RasterSourceIT:
[info] RasterSource.readAll
[info] Done compiling.
[info] - should return consistently ordered tiles across bands for a given scene (27 seconds, 224 milliseconds)
[info] GDAL support
[info] - should read JPEG2000 scene (5 seconds, 149 milliseconds)
[info] - should read small MRF scene with one band converted from MODIS HDF (291 milliseconds)
[info] - should read remote HTTP MRF scene (2 minutes, 39 seconds)
[info] - should read remote S3 MRF scene (4 minutes, 53 seconds)
```

**Comment by metasim** [comment]
Primary bug is due to a bad cache file in CircleCI. Fixed by `rm -r ~/.rf_cache`.

**Comment by metasim** [comment]
Primary bug addressed in 3b7bfa8d5594f73386591e5f8304e5215833f07c.
Output oddity in section output is logged here: https://github.com/geotrellis/gdal-warp-bindings/issues/53

**Comment by metasim** [comment]
https://circleci.com/gh/s22s/rasterframes/825

**Comment by vpipkt** [comment]
awesome, same thing locally.
