### ISSUE TITLE
rf-notebooks instructions for accessing s3 buckets

### ISSUE THREAD

**Issue by vpipkt** [locationtech/rasterframes#266]
Even with gdal properly configured... I seem to (on the notebook side) get silent errors with reading GDAL sources of the `gdal://vsis3` variety. Here's what i see in the `docker logs`

So would be good to instruct users how to set this up. 

```
ERROR 15: AWS_SECRET_ACCESS_KEY and AWS_NO_SIGN_REQUEST configuration options not defined, and /home/jovyan/.aws/credentials not filled
2019-08-08 15:54:30 ERROR RasterSourceToRasterRefs:77 - Error fetching data for one of: GDALRasterSource(s3://sentinel-s2-l2a/tiles/31/T/CF/2019/7/12/0/R60m/B04.jp2)
java.lang.Exception: get_transform or get_widht_height
	at geotrellis.contrib.vlm.gdal.GDALDataset$.rasterExtent$extension1(GDALDataset.scala:45)
	at geotrellis.contrib.vlm.gdal.GDALDataset$.rasterExtent$extension0(GDALDataset.scala:37)
	at geotrellis.contrib.vlm.gdal.GDALBaseRasterSource$class.rasterExtent(GDALBaseRasterSource.scala:69)
	at geotrellis.contrib.vlm.gdal.GDALRasterSource.rasterExtent$lzycompute(GDALRasterSource.scala:22)
	at geotrellis.contrib.vlm.gdal.GDALRasterSource.rasterExtent(GDALRasterSource.scala:22)
```

**Comment by vpipkt** [comment]
A possibility would be for the user to mount their ~/.aws in the container. No idea bout security concerns around that.
