### ISSUE TITLE
supervised-learning.pymd fails after RasterRef GridBounds expansion

### ISSUE THREAD

**Issue by metasim** [locationtech/rasterframes#304]
Appears to have stopped working after 67108de48fb919b8124533517bacd1f4826968a8

```python
model = pipeline.fit(df_mask.filter(rf_tile_sum('label') > 0).cache())
```

```
---------------------------------------------------------------------------Py4JJavaError                             Traceback (most recent call last)<ipython-input-1-04772a34de7f> in <module>()
----> 1 model = pipeline.fit(df_mask.filter(rf_tile_sum('label') > 0).cache())
/anaconda3/lib/python3.6/site-packages/pyspark/ml/base.py in fit(self, dataset, params)
    130                 return self.copy(params)._fit(dataset)
    131             else:
--> 132                 return self._fit(dataset)
    133         else:
    134             raise ValueError("Params must be either a param map or a list/tuple of param maps, "
/anaconda3/lib/python3.6/site-packages/pyspark/ml/pipeline.py in _fit(self, dataset)
    107                     dataset = stage.transform(dataset)
    108                 else:  # must be an Estimator
--> 109                     model = stage.fit(dataset)
    110                     transformers.append(model)
    111                     if i < indexOfLastEstimator:
/anaconda3/lib/python3.6/site-packages/pyspark/ml/base.py in fit(self, dataset, params)
    130                 return self.copy(params)._fit(dataset)
    131             else:
--> 132                 return self._fit(dataset)
    133         else:
    134             raise ValueError("Params must be either a param map or a list/tuple of param maps, "
/anaconda3/lib/python3.6/site-packages/pyspark/ml/wrapper.py in _fit(self, dataset)
    286 
    287     def _fit(self, dataset):
--> 288         java_model = self._fit_java(dataset)
    289         model = self._create_model(java_model)
    290         return self._copyValues(model)
/anaconda3/lib/python3.6/site-packages/pyspark/ml/wrapper.py in _fit_java(self, dataset)
    283         """
    284         self._transfer_params_to_java()
--> 285         return self._java_obj.fit(dataset._jdf)
    286 
    287     def _fit(self, dataset):
/anaconda3/lib/python3.6/site-packages/py4j/java_gateway.py in __call__(self, *args)
   1255         answer = self.gateway_client.send_command(command)
   1256         return_value = get_return_value(
-> 1257             answer, self.gateway_client, self.target_id, self.name)
   1258 
   1259         for temp_arg in temp_args:
/anaconda3/lib/python3.6/site-packages/pyspark/sql/utils.py in deco(*a, **kw)
     61     def deco(*a, **kw):
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:
     65             s = e.java_exception.toString()
/anaconda3/lib/python3.6/site-packages/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:
    330                 raise Py4JError(
Py4JJavaError: An error occurred while calling o638.fit.
: java.lang.NullPointerException: Value at index 0 is null
	at org.apache.spark.sql.Row$class.getAnyValAs(Row.scala:472)
	at org.apache.spark.sql.Row$class.getDouble(Row.scala:248)
	at org.apache.spark.sql.catalyst.expressions.GenericRow.getDouble(rows.scala:166)
	at org.apache.spark.ml.classification.Classifier.getNumClasses(Classifier.scala:115)
	at org.apache.spark.ml.classification.DecisionTreeClassifier.train(DecisionTreeClassifier.scala:102)
	at org.apache.spark.ml.classification.DecisionTreeClassifier.train(DecisionTreeClassifier.scala:45)
	at org.apache.spark.ml.Predictor.fit(Predictor.scala:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by metasim** [comment]
I've definitely had this problem before, involving `org.apache.spark.ml.classification.Classifier.getNumClasses`.

Here's more detail: https://issues.apache.org/jira/browse/SPARK-23152

**Comment by metasim** [comment]
Bug exists in 68a8e866006ccc15cdc32e8a8d5fdf58ab89694c

**Comment by metasim** [comment]
Code does **not** exist in 721cc47c59230f114762553f92546156b63a30c4

**Comment by vpipkt** [comment]
So basically the dataframe `df_mask` has no rows or the label column is null?

**Comment by metasim** [comment]
Bug was with changes to `rf_with_no_data` handling acceptance of either `Double` or `Int`, and then incorrectly changing floating point tiles into a float cell type.

**Comment by vpipkt** [comment]
> Bug was with changes to `rf_with_no_data` handling acceptance of either `Double` or `Int`, and then incorrectly changing floating point tiles into a float cell type.

Maybe you meant "incorrectly changing floating point tiles to int" or "...int tile to float"?

**Comment by metasim** [comment]
> Maybe you meant "incorrectly changing floating point tiles to int" or "...int tile to float"?

I meant incorrectly turning an integral tile into a floating point one.
