### ISSUE TITLE
RasterSource reader handling of heterogeneous resolution across catalog columns

### ISSUE THREAD

**Issue by vpipkt** [locationtech/rasterframes#326]
In some cases the user wittingly wants to create a catalog row where the columns contain URIs for rasters of different resolutions, but the same extent. Consider Landsat 8 band 8 (15m panchromatic) and other OLI bands (30m) or Sentinel 2 VNIR bands are 10m but many other bands are 20m or 60m. 

Currently attempting to read such a catalog fails, as example stack trace below. Another consideration is that any local ops across such tile columns of unequal dimensions would also fail.

A current work around would be to make individual catalogs for each resolution, making careful use of the tileDimensions param, then try to join on extents.

A proposed solution:

In the RasterSource reader, use the first column's (or the col with the finest resolution) extent/resolution to set the gridding and extents to read for all the other columns. This will result in the same number of rows generated from each catalog row.

A further nice to have may be a way for the user to express if / how they want resampling so all tile columns are at the same resolution. A sensible enough default might be for nearest neighbor upsampling to the finest resolution column.

```
 ERROR RasterSourceToRasterRefs:81 - Error fetching data for one of: GDALRasterSource(s3://sentinel-s2-l2a/tiles/19/H/BE/2019/7/23/0/R60m/B12.jp2), GDALRasterSource(s3://sentinel-s2-l2a/tiles/19/H/BE/2019/7/23/0/R20m/SCL.jp2)
java.lang.IllegalArgumentException: transpose requires all collections have the same size
        at scala.collection.generic.GenericTraversableTemplate$class.fail$1(GenericTraversableTemplate.scala:213)
        at scala.collection.generic.GenericTraversableTemplate$$anonfun$transpose$1$$anonfun$apply$1.apply(GenericTraversableTemplate.scala:220)
        at scala.collection.generic.GenericTraversableTemplate$$anonfun$transpose$1$$anonfun$apply$1.apply(GenericTraversableTemplate.scala:219)
        at scala.collection.immutable.Stream.foreach(Stream.scala:594)
```

**Comment by vpipkt** [comment]
DUPE #174
