### ISSUE TITLE
hadoop aws depenencies in rasterframes-notebooks

### ISSUE THREAD

**Issue by vpipkt** [locationtech/rasterframes#38]
Add hadoop aws dependencies for accessing data via s3a in the rasterframes-notebooks build.

May also be good to show this in an example, including authorization.

**Comment by vpipkt** [comment]
Issue is stale. We can read successfully with the following:

* 👌 `https://${bucket}.s3.${region}.amazonaws.com/${prefix}`
*  👌 `s3://${bucket}/${prefix}`
* 👌 `gdal://vsis3/${bucket}/${prefix}`  ** caveat if there is an appropriate ~/.aws/credentials file in the container see https://github.com/locationtech/rasterframes/issues/266 

But not this:

* ❌ `s3a://${bucket}/${prefix}`

The errror we see on stderr is below. This all seems consistent with documented use of HDFS versus GDAL schemes and such. Will file a new issue to clarify the fix for this.

```
ERROR 4: landsat-pds/c1/L8/190/028/LC08_L1TP_190028_20190705_20190719_01_T1/LC08_L1TP_190028_20190705_20190719_01_T1_B8.TIF: No such file or directory
2019-08-23 17:39:45 ERROR RasterSourceToRasterRefs:77 - Error fetching data for one of: GDALRasterSource(s3a://landsat-pds/c1/L8/190/028/LC08_L1TP_190028_20190705_20190719_01_T1/LC08_L1TP_190028_20190705_20190719_01_T1_B8.TIF)
java.lang.Exception: get_transform or get_widht_height
	at geotrellis.contrib.vlm.gdal.GDALDataset$.rasterExtent$extension1(GDALDataset.scala:45)
	at geotrellis.contrib.vlm.gdal.GDALDataset$.rasterExtent$extension0(GDALDataset.scala:37)
	at geotrellis.contrib.vlm.gdal.GDALBaseRasterSource$class.rasterExtent(GDALBaseRasterSource.scala:69)
	at geotrellis.contrib.vlm.gdal.GDALRasterSource.rasterExtent$lzycompute(GDALRasterSource.scala:22)
	at geotrellis.contrib.vlm.gdal.GDALRasterSource.rasterExtent(GDALRasterSource.scala:22)
	at geotrellis.contrib.vlm.RasterSource$class.cols(RasterSource.scala:76)
...
...
...
```
