### ISSUE TITLE
RGBComposite throws exception during normalization process. 

### ISSUE THREAD

**Issue by metasim** [locationtech/rasterframes#387]
Suspicion is this is caused by a NoData tile, or a tile where all the values are zero.
```
org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 9.0 failed 4 times, most recent failure: Lost task 0.3 in stage 9.0 (TID 12, 10.0.187.204, executor 1): java.lang.RuntimeException: Invalid parameters: 0, 0, 0, 255
	at scala.sys.package$.error(package.scala:27)
	at geotrellis.raster.Tile$class.normalize(Tile.scala:245)
	at org.locationtech.rasterframes.ref.RasterRef$RasterRefTile.normalize(RasterRef.scala:63)
	at geotrellis.raster.Tile$class.rescale(Tile.scala:271)
	at org.locationtech.rasterframes.ref.RasterRef$RasterRefTile.rescale(RasterRef.scala:63)
	at org.locationtech.rasterframes.expressions.transformers.RGBComposite.nullSafeEval(RGBComposite.scala:87)
```

**Comment by vpipkt** [comment]
Related #458
