### ISSUE TITLE
Failures in `pytest` are not detected by `sbt test`

### ISSUE THREAD

**Issue by metasim** [locationtech/rasterframes#40]
Partial sbt session. You can see that `pytest` noted a test failure, but sbt things everything passed.

```
[info] running pytest
[info] Searching for pytest==3.4.2
[info] Best match: pytest 3.4.2
[info] Processing pytest-3.4.2-py3.6.egg
[info] Using /Users/sfitch/Coding/OSS/locationtech-rasterframes/pyrasterframes/python/.eggs/pytest-3.4.2-py3.6.egg
[info] running egg_info
[info] writing pyrasterframes.egg-info/PKG-INFO
[info] writing dependency_links to pyrasterframes.egg-info/dependency_links.txt
[info] writing top-level names to pyrasterframes.egg-info/top_level.txt
[info] reading manifest file 'pyrasterframes.egg-info/SOURCES.txt'
[info] writing manifest file 'pyrasterframes.egg-info/SOURCES.txt'
[info] running build_ext
[info] ============================= test session starts ==============================
[info] platform darwin -- Python 3.6.4, pytest-3.4.2, py-1.5.2, pluggy-0.6.0 -- /anaconda3/bin/python
[info] cachedir: .pytest_cache
[info] rootdir: /Users/sfitch/Coding/OSS/locationtech-rasterframes/pyrasterframes/python, inifile: setup.cfg
[info] collecting ... collected 5 items
[info] tests/PyRasterFramesTests.py::RasterFunctionsTest::test_aggregations PASSED [ 20%]
[info] tests/PyRasterFramesTests.py::RasterFunctionsTest::test_general FAILED   [ 40%]
[info] tests/PyRasterFramesTests.py::RasterFunctionsTest::test_identify_columns PASSED [ 60%]
[info] tests/PyRasterFramesTests.py::RasterFunctionsTest::test_sql PASSED       [ 80%]
[info] tests/PyRasterFramesTests.py::RasterFunctionsTest::test_tile_operations PASSED [100%]
[info] =================================== FAILURES ===================================
[info] _______________________ RasterFunctionsTest.test_general _______________________
[info] self = <PyRasterFramesTests.RasterFunctionsTest testMethod=test_general>
[info]     def test_general(self):
[info]         meta = self.rf.tileLayerMetadata()
[info]         self.assertIsNotNone(meta['bounds'])
[info]         df = self.rf.withColumn('dims',  tileDimensions(self.tileCol)) \
[info]             .withColumn('type', cellType(self.tileCol)) \
[info]             .withColumn('dCells', dataCells(self.tileCol)) \
[info]             .withColumn('ndCells', noDataCells(self.tileCol)) \
[info]             .withColumn('min', tileMin(self.tileCol)) \
[info]             .withColumn('max', tileMax(self.tileCol)) \
[info]             .withColumn('mean', tileMean(self.tileCol)) \
[info]             .withColumn('sum', tileSum(self.tileCol)) \
[info]             .withColumn('stats', tileStats(self.tileCol)) \
[info] >           .withColumn('box2D', box2D('bounds')) \
[info]             .withColumn('ascii', renderAscii(self.tileCol))
[info] tests/PyRasterFramesTests.py:93: 
[info] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[info] pyrasterframes/rasterfunctions.py:249: in _
[info]     return Column(jfcn(*jcols))
[info] .eggs/py4j-0.10.4-py3.6.egg/py4j/java_gateway.py:1133: in __call__
[info]     answer, self.gateway_client, self.target_id, self.name)
[info] .eggs/pyspark-2.1.2-py3.6.egg/pyspark/sql/utils.py:63: in deco
[info]     return f(*a, **kw)
[info] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[info] answer = 'xspy4j.Py4JException: Method box2D([class org.apache.spark.sql.Column]) does not exist\\n\tat py4j.reflection.Reflect...java:79)\\n\tat py4j.GatewayConnection.run(GatewayConnection.java:214)\\n\tat java.lang.Thread.run(Thread.java:748)\\n'
[info] gateway_client = <py4j.java_gateway.GatewayClient object at 0x1043de588>
[info] target_id = 'o20', name = 'box2D'
[info]     def get_return_value(answer, gateway_client, target_id=None, name=None):
[info]         """Converts an answer received from the Java gateway into a Python object.
[info]     
[info]         For example, string representation of integers are converted to Python
[info]         integer, string representation of objects are converted to JavaObject
[info]         instances, etc.
[info]     
[info]         :param answer: the string returned by the Java gateway
[info]         :param gateway_client: the gateway client used to communicate with the Java
[info]             Gateway. Only necessary if the answer is a reference (e.g., object,
[info]             list, map)
[info]         :param target_id: the name of the object from which the answer comes from
[info]             (e.g., *object1* in `object1.hello()`). Optional.
[info]         :param name: the name of the member from which the answer comes from
[info]             (e.g., *hello* in `object1.hello()`). Optional.
[info]         """
[info]         if is_error(answer)[0]:
[info]             if len(answer) > 1:
[info]                 type = answer[1]
[info]                 value = OUTPUT_CONVERTER[type](answer[2:], gateway_client)
[info]                 if answer[1] == REFERENCE_TYPE:
[info]                     raise Py4JJavaError(
[info]                         "An error occurred while calling {0}{1}{2}.\n".
[info]                         format(target_id, ".", name), value)
[info]                 else:
[info]                     raise Py4JError(
[info]                         "An error occurred while calling {0}{1}{2}. Trace:\n{3}\n".
[info] >                       format(target_id, ".", name, value))
[info] E                   py4j.protocol.Py4JError: An error occurred while calling o20.box2D. Trace:
[info] E                   py4j.Py4JException: Method box2D([class org.apache.spark.sql.Column]) does not exist
[info] E                   	at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:318)
[info] E                   	at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:326)
[info] E                   	at py4j.Gateway.invoke(Gateway.java:272)
[info] E                   	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[info] E                   	at py4j.commands.CallCommand.execute(CallCommand.java:79)
[info] E                   	at py4j.GatewayConnection.run(GatewayConnection.java:214)
[info] E                   	at java.lang.Thread.run(Thread.java:748)
[info] .eggs/py4j-0.10.4-py3.6.egg/py4j/protocol.py:323: Py4JError
[info] ===================== 1 failed, 4 passed in 16.69 seconds ======================

...


[info] - should read geometry                                                   
[info] Run completed in 4 minutes, 8 seconds.
[info] Total number of tests run: 85
[info] Suites: completed 14, aborted 0
[info] Tests: succeeded 85, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[info] Run completed in 3 minutes, 55 seconds.
[info] Total number of tests run: 40
[info] Suites: completed 4, aborted 0
[info] Tests: succeeded 40, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[info] Run completed in 3 minutes, 49 seconds.
[info] Total number of tests run: 6
[info] Suites: completed 2, aborted 0
[info] Tests: succeeded 6, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[success] Total time: 266 s, completed May 31, 2018 10:52:25 AM
sbt:RasterFrames> 
```

**Comment by bguseman** [comment]
Updated build to fail test task on python test failures.
