### ISSUE TITLE
java.lang.NoClassDefFoundError: org/apache/commons/httpclient/HttpMethodBase

### ISSUE THREAD

**Issue by jornfranke** [locationtech/rasterframes#546]
Pyrasterframe 0.9.0
Spark: 2.4.0

Source to reproduce
```
from pyrasterframes.utils import create_rf_spark_session
spark = create_rf_spark_session()
df = spark.read.raster("hdfs://..../U2018_CLC2018_V2020_20u1.tif")
```

Error
```
Py4JJavaError: An error occurred while calling o113.load.
: java.lang.NoClassDefFoundError: org/apache/commons/httpclient/HttpMethodBase
    at org.locationtech.rasterframes.experimental.datasource.awspds.L8CatalogDataSource$.<init>(L8CatalogDataSource.scala:50)
    at org.locationtech.rasterframes.experimental.datasource.awspds.L8CatalogDataSource$.<clinit>(L8CatalogDataSource.scala)
    at org.locationtech.rasterframes.experimental.datasource.awspds.L8CatalogDataSource.shortName(L8CatalogDataSource.scala:38)
    at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$18.apply(DataSource.scala:624)
    at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$18.apply(DataSource.scala:624)
    at scala.collection.TraversableLike$$anonfun$filterImpl$1.apply(TraversableLike.scala:248)
    at scala.collection.Iterator$class.foreach(Iterator.scala:891)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
    at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
    at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
    at scala.collection.TraversableLike$class.filterImpl(TraversableLike.scala:247)
    at scala.collection.TraversableLike$class.filter(TraversableLike.scala:259)
    at scala.collection.AbstractTraversable.filter(Traversable.scala:104)
    at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSource(DataSource.scala:624)
    at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:194)
    at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:178)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
    at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
    at py4j.Gateway.invoke(Gateway.java:282)
    at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
    at py4j.commands.CallCommand.execute(CallCommand.java:79)
    at py4j.GatewayConnection.run(GatewayConnection.java:238)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.httpclient.HttpMethodBase
    at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
    ... 27 more


```

It is just the local master and it seems the class is rather outdated. I am also not sure why it uses awspds, it is a geotiff on HDFS.

**Comment by jornfranke** [comment]
Found it. Some experimental code that is also in the standard library uses an extremely outdated httpclient:
https://github.com/locationtech/rasterframes/blob/develop/experimental/src/main/scala/org/locationtech/rasterframes/experimental/datasource/DownloadSupport.scala

You find the jar in maven central here: https://mvnrepository.com/artifact/commons-httpclient/commons-httpclient


This has been replaced more than 10 years ago by the following: https://mvnrepository.com/artifact/org.apache.httpcomponents/httpclient

I recommend to change this in the source code and include the new httpclient in the buildfiles. The old one is also to likely fail soon in any case as it supports only outdated http protocols.

As a workaround I include the old httpclient (shaded, but I guess it does not matter) in the fatjar/uberjar

**Comment by metasim** [comment]
@jornfranke Thanks for the tip on httpclient being outdated. That experimental code is a hack anyway, and shouldn't be included in the official distribution.... I'd take `rasterframes-experimental` out of your classpath, or use the assembly generated as a part of the pyrasterframes distribution.

**Comment by abhishekkrbaliase** [comment]
@metasim How can we take it out in our production environement? We are using pyrasterframes 0.9.1 

We are launching it using below command
`pyspark --py-files pyrasterframes_2.11-${VERSION}-python.zip --packages org.locationtech.rasterframes:rasterframes_2.11:${VERSION},org.locationtech.rasterframes:pyrasterframes_2.11:${VERSION},org.locationtech.rasterframes:rasterframes-datasource_2.11:${VERSION} --conf spark.serializer=org.apache.spark.serializer.KryoSerializer --conf spark.kryo.registrator=org.locationtech.rasterframes.util.RFKryoRegistrator --conf spark.kryoserializer.buffer.max=500m`

**Comment by bergaminrafael** [comment]
I'm having the same problem as described by OP but I'm on 0.9.1. Installed the package with pip. I've tried to download the commons-httpclient jar from mvnrepository to a folder in SPARK_DIST_CLASSPATH, to no success.

@metasim would to care to shed some light to this passage: 

> I'd take rasterframes-experimental out of your classpath

Which classpath would this be?

My tests:

Pyrasterframe 0.9.1
Spark: 2.4.5

running:

```
from pyrasterframes.utils import create_rf_spark_session
spark = create_rf_spark_session()
uri = 'https://modis-pds.s3.amazonaws.com/MCD43A4.006/11/08/2019059/MCD43A4.A2019059.h11v08.006.2019072203257_B02.TIF'
spark.read.raster(uri)
```

output:

```
Py4JJavaError: An error occurred while calling o66.load.
: java.lang.NoClassDefFoundError: org/apache/commons/httpclient/HttpMethodBase
	at org.locationtech.rasterframes.experimental.datasource.awspds.L8CatalogDataSource$.<init>(L8CatalogDataSource.scala:50)
	at org.locationtech.rasterframes.experimental.datasource.awspds.L8CatalogDataSource$.<clinit>(L8CatalogDataSource.scala)
	at org.locationtech.rasterframes.experimental.datasource.awspds.L8CatalogDataSource.shortName(L8CatalogDataSource.scala:38)
	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$18.apply(DataSource.scala:630)
	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$18.apply(DataSource.scala:630)
	at scala.collection.TraversableLike$$anonfun$filterImpl$1.apply(TraversableLike.scala:248)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.filterImpl(TraversableLike.scala:247)
	at scala.collection.TraversableLike$class.filter(TraversableLike.scala:259)
	at scala.collection.AbstractTraversable.filter(Traversable.scala:104)
	at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSource(DataSource.scala:630)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:194)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:178)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.httpclient.HttpMethodBase
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 27 more
```

**Comment by jornfranke** [comment]
It is bit weird, I can see your comments in my email inbox, but not on
Github. Removing experimental from the classpath does not help as
originally explained. I created my own fat jar of rasterframes and sharded
the old HTTP client. I can share a build.sbt for this tomorrow.

**Comment by abhishekkrbaliase** [comment]
I just passes the http client Jar to spark using --jar and it stopped
giving me these errors

Thus, deleted the comment


- Abhishek Kumar
